#!/bin/bash
#PBS -N just_gubbins_GPSC14
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=16:mem=32gb


source ~/anaconda3/etc/profile.d/conda.sh
conda activate gubbins_updated

WORKDIR="/rds/general/user/dac23/home/pneumo_2026_23F"
FASTA_DIR="$WORKDIR/raw_data/gubbins_input_gpsc14"
REF_DIR="$WORKDIR/inputs"
OUTDIR="$WORKDIR/outputs/gubbins"

echo "Running Gubbins (will take a long time)"
run_gubbins.py \
  --prefix "$OUTDIR/gpsc14_" \
  "$OUTDIR/aligned_all_isolates.aln"

echo "Done!"
