#!/bin/bash
#PBS -N gubbins_GPSC14
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=16:mem=32gb


source ~/anaconda3/etc/profile.d/conda.sh
conda activate gubbins_updated

WORKDIR="/rds/general/user/dac23/home/pneumo_2026_23F"
FASTA_DIR="$WORKDIR/raw_data/gubbins_input_gpsc14"
REF_DIR="$WORKDIR/inputs"
OUTDIR="$WORKDIR/outputs/gubbins"

mkdir -p "$FASTA_DIR" "$REF_DIR" "$OUTDIR"
cd "$FASTA_DIR" || { echo "ERROR: cannot cd to $FASTA_DIR"; exit 1; }


for file in "$FASTA_DIR"/*.fasta; do
  echo -e "$(basename ${file%.fasta})\t${file}"
done > "$OUTDIR/gubbins_target.list"

if [ ! -s "$OUTDIR/gubbins_target.list" ]; then
  echo "ERROR: gubbins_target.list is empty — no .fasta files found in $FASTA_DIR"
  exit 1
fi

# reference genome was personally downloaded
# wget -q -O "$REF_DIR/Strep_ATCC700669_Ref.fasta" \
#   "https://www.ebi.ac.uk/ena/browser/api/fasta/FM211187.1?download=true"

generate_ska_alignment.py \
  --reference "$REF_DIR/GPSC14_reference.fasta" \
  --input "$OUTDIR/gubbins_target.list" \
  --out "$OUTDIR/aligned_all_isolates.aln"

echo "Running Gubbins (will take a long time)"
run_gubbins.py \
  --prefix "$OUTDIR/gpsc14_" \
  "$OUTDIR/aligned_all_isolates.aln"

echo "Done!"
